version: "3.8"
services:
  redis-docker:
    build: ./redis
    command: redis-server --port 6379
    restart: always
    container_name: pintalk-redis
    volumes:
      - pintalk-redis-vol:/data
    ports:
      - 6379:6379
  db:
    image: mysql:latest
    container_name: pintalk-db
    ports:
      - "3306:3306"
#    command:
#      - --default-authentication-plugin=mysql_native_password
#      - --character-set-server=utf8mb4
#      - --collation-server=utf8mb4_unicode_ci
    volumes:
#      - ./mysql/conf.d:/etc/mysql/conf.d
#      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
      - pintalk-mysql-vol:/var/lib/mysql
    environment:
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: pintalk
      TZ: Asia/Seoul
  api:
    build: .
    container_name: pintalk-api
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: always

  server:
    build: ./nginx
    container_name: pintalk-nginx
    ports:
      - "80:80"
    restart: always
volumes:
  pintalk-redis-vol:
  pintalk-mysql-vol:
