version: "3.8"
services:
  redis-docker:
    image: pintalk-redis
    command: redis-server --port 6379
    restart: always
    container_name: pintalk-redis
    labels:
      - "name=pintalk-redis"
    volumes:
      - /Users/jisoo/Desktop/dev/playidea/PinkTalk/PinTalk-API/redis/redis_data:/data
    ports:
      - 6379:6379