version: "3.8"
services:
  redis:
    build: infra/redis
    command: redis-server --port 6379
    restart: always
    container_name: pintalk-redis
    volumes:
      - pintalk-redis:/data
    ports:
      - 6379:6379
  db:
    image: mysql:latest
    container_name: pintalk-db
    restart: always
    ports:
      - "3306:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - pintalk-mysql:/var/lib/mysql
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}

  api:
    build: .
    container_name: pintalk-api
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: always
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.deploy

  server:
    build: infra/nginx
    container_name: pintalk-nginx
    ports:
      - "80:80"
    restart: always
volumes:
  pintalk-redis:
  pintalk-mysql: