version: "3.8"
services:
  redis:
    build: ./redis
    command: redis-server --port 6379
    restart: always
    container_name: pintalk-redis
    volumes:
      - /home/ubuntu/pintalk-data/redis:/data
    ports:
      - 6379:6379
  db:
    image: mysql:latest
    container_name: pintalk-db
    ports:
      - "3306:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - /home/ubuntu/pintalk-data/mysql:/var/lib/mysql
    environment:
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: pintalk
      TZ: Asia/Seoul
  api:
    build: .
    container_name: pintalk-api
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: always

  server:
    build: ./nginx
    container_name: pintalk-nginx
    ports:
      - "80:80"
    restart: always
