version: "3.8"
services:
  redis:
    build: ./redis
    command: redis-server --port 6379
    restart: always
    container_name: pintalk-redis
    volumes:
      - /home/ubuntu/pintalk-data/redis:/data
    ports:
      - 6379:6379
  db:
    image: mysql:latest
    container_name: pintalk-db
    ports:
      - "3306:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - /home/ubuntu/pintalk-data/mysql:/var/lib/mysql
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}

  api:
    build: .
    container_name: pintalk-api
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: always
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - DB_PASSWORD=linda2927
      - AWS_S3_USER_ACCESS_KEY_ID=${AWS_S3_USER_ACCESS_KEY_ID}
      - AWS_S3_USER_SECRET_ACCESS_KEY=${AWS_S3_USER_SECRET_ACCESS_KEY}
      - AWS_STORAGE_BUCKET_NAME=${AWS_STORAGE_BUCKET_NAME}
      - AWS_S3_REGION_NAME=${AWS_S3_REGION_NAME}

  server:
    build: ./nginx
    container_name: pintalk-nginx
    ports:
      - "80:80"
    restart: always
