# Generated by Django 4.1.4 on 2022-12-26 01:48

import apps.user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=64, unique=True)),
                ("access_key", models.CharField(max_length=22)),
                ("secret_key", models.CharField(max_length=64)),
                ("service_name", models.CharField(max_length=50)),
                ("service_expl", models.CharField(max_length=200)),
            ],
            options={
                "db_table": "user",
                "unique_together": {("email",)},
            },
            managers=[
                ("objects", apps.user.models.UserManager()),
            ],
        ),
    ]
