# Generated by Django 4.1.5 on 2023-01-06 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="service_domain",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
