# Generated by Django 4.1.4 on 2023-01-03 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_user_groups_user_is_superuser_user_user_permissions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="description",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_name",
            field=models.CharField(default="Admin", max_length=50),
            preserve_default=False,
        ),
    ]
