# Generated by Django 4.1.5 on 2023-01-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_user_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(null=True, upload_to="user_profiles/"),
        ),
    ]
