# Generated by Django 4.1.5 on 2023-03-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_user_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="description",
            field=models.CharField(blank=True, default="", max_length=200, null=True),
        ),
    ]
