# Generated by Django 4.1.4 on 2023-01-03 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_remove_user_is_deleted_user_is_staff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_name",
            field=models.CharField(
                blank=True, default=models.CharField(max_length=50), max_length=50
            ),
        ),
    ]
