# Generated by Django 4.1.5 on 2023-03-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_userconfiguration"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="uuid",
            field=models.CharField(default="NsNVwaNrkUbrgnkGfsTuuA", max_length=22),
            preserve_default=False,
        ),
    ]
