# Generated by Django 4.1.5 on 2023-04-21 10:23

import apps.user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_user_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(
                null=True, upload_to=apps.user.models.modify_profile_image_filename
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="userconfiguration",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
