# Generated by Django 4.1.5 on 2023-04-21 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0008_alter_user_profile_image_alter_user_updated_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_deleted",
        ),
    ]
