# Generated by Django 4.1.5 on 2023-04-26 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0010_user_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="deleted_at",
            field=models.DateTimeField(null=True),
        ),
    ]
