# Generated by Django 4.1.5 on 2023-05-08 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0012_alter_userconfiguration_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userconfiguration",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="configs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
