# Generated by Django 4.1.5 on 2023-01-05 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatroom",
            name="latest_msg",
        ),
        migrations.RemoveField(
            model_name="chatroom",
            name="visitor",
        ),
        migrations.AddField(
            model_name="chatroom",
            name="guest",
            field=models.CharField(default="guest123", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="chatroom",
            name="name",
            field=models.CharField(default="playidea:guest123123", max_length=50),
            preserve_default=False,
        ),
    ]
