# Generated by Django 4.1.5 on 2023-01-16 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_remove_chatroom_latest_msg_remove_chatroom_visitor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="latest_msg",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="latest_msg",
                to="chat.chatmessage",
            ),
        ),
        migrations.AlterField(
            model_name="chatroom",
            name="name",
            field=models.CharField(max_length=22),
        ),
    ]
