# Generated by Django 4.1.5 on 2023-01-22 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_chatroom_latest_msg_alter_chatroom_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="deleted_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="chatroom",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="chat.chatroom"
            ),
        ),
    ]
