# Generated by Django 4.1.5 on 2023-03-18 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_chatroom_deleted_at_chatroom_is_deleted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="is_closed",
            field=models.BooleanField(default=False),
        ),
    ]
