# Generated by Django 4.1.5 on 2023-03-22 00:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0008_chatroom_fixed_at_chatroom_is_fixed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatmessage",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="chatmessage",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="datetime",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
