# Generated by Django 4.1.5 on 2023-03-22 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0009_remove_chatmessage_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="last_checked_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="chatroom",
            name="latest_msg",
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
