# Generated by Django 4.1.5 on 2023-03-22 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0010_chatroom_last_checked_at_alter_chatroom_latest_msg"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="latest_msg_at",
            field=models.DateTimeField(null=True),
        ),
    ]
