# Generated by Django 4.1.5 on 2023-04-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0011_chatroom_latest_msg_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatroom",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
