# Generated by Django 4.1.5 on 2023-05-05 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0012_alter_chatroom_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatroom",
            name="fixed_at",
        ),
        migrations.RemoveField(
            model_name="chatroom",
            name="is_fixed",
        ),
    ]
